<?php $this->headTitle()->set('add'); ?>
<div id="add">
  <?php if(isset($messages)):?>
    <?php foreach($messages as $message):?>
      <?php echo $message; ?>
    <?php endforeach; ?>
  <?php endif; ?>
  <form id="addform" action="add/insert" method="post">
    <table>
      <tr><td>Name ： <input type="text" name="name" /></td></tr>
    </table>
    <input type="submit" name="submit" value="登録" />
  </form>
</div>
